version: "3.9"

services:
  backend:
    build: .
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db       # persist SQLite database
      - ./data:/app/data   # mount ai_act.yaml folder
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
